/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*package view;

import controller.ContractCtrl;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Contract;
import model.ContractTableModel;

import model.Login;

/**
 *
 * @author greg
 */
/*
public class ContractWindow extends javax.swing.JPanel {

    private NewMainMenu newMenu;
    private Login userLogged;
    private ContractCtrl contractCtrl;
    private List<Contract> contractList;
    private ContractTableModel table;
    private int selectedRow = 0;
    

    /**
     * Creates new form ContractWindow
     */
  /*  
    public ContractWindow(int y, Login user) {
        userLogged = user;
        
        this.contractCtrl = new ContractCtrl();
        this.table = new ContractTableModel();
        
        try {
            this.contractList = this.contractCtrl.readContract();
            this.table.addContractList(this.contractList);
        } catch (SQLException ex) {
            Logger.getLogger(ContractWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        //jTable1.setValueAt(table, y, y);
        initComponents();
        setSize(1024, y);
    
    }

    private void clean() {
        outPeakDemandContractedField.setText("");
        peakDemandContractedField.setText("");
        drySeasonComboBox.setSelectedIndex(0);
        humidSeasonComboBox.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
/*
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        insertPanel = new javax.swing.JPanel();
        passwrod2Label = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        cell_vivoLabel = new javax.swing.JLabel();
        peakDemandContractedField = new javax.swing.JTextField();
        cell_timLabel = new javax.swing.JLabel();
        warningLabel = new javax.swing.JLabel();
        createGuidelineButton = new javax.swing.JButton();
        outPeakDemandContractedField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        drySeasonComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        humidSeasonComboBox = new javax.swing.JComboBox();
        editPanel = new javax.swing.JPanel();
        guidelineComboBoxEdition = new javax.swing.JComboBox();
        nameLabel1 = new javax.swing.JLabel();
        categoryComboBoxEdition = new javax.swing.JComboBox();
        registerLabel1 = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        passwrod2Label1 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        outPeakEnergyDryFieldEdition = new javax.swing.JTextField();
        cell_oiLabel1 = new javax.swing.JLabel();
        cell_vivoLabel1 = new javax.swing.JLabel();
        outPeakEnergyHumidFieldEdition = new javax.swing.JTextField();
        peakDemandFieldEdition = new javax.swing.JTextField();
        cell_timLabel1 = new javax.swing.JLabel();
        cell_claroLabel1 = new javax.swing.JLabel();
        peakEnergyDryFieldEdition = new javax.swing.JTextField();
        peakEnergyHumidFieldEdition = new javax.swing.JTextField();
        profileLabel2 = new javax.swing.JLabel();
        warningLabel1 = new javax.swing.JLabel();
        editGuidelineButton = new javax.swing.JButton();
        outPeakDemandFieldEdition = new javax.swing.JTextField();
        profileLabel3 = new javax.swing.JLabel();
        valueTranspassedFieldEdition = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        readPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backToMainMenu = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bitstream Charter", 0, 24))); // NOI18N

        passwrod2Label.setText("Demanda Contratada Fora de Ponta*:");

        cell_timLabel.setText("Demanda Contrada em Ponta*:");

        warningLabel.setText("<html>Os campos assinalados com asterisco (*) <br>são de preencimento obrigatório</html>");

        createGuidelineButton.setText("Cadastrar");
        createGuidelineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGuidelineButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Início do Período Seco*:");

        drySeasonComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        jLabel2.setText("Início do Período Úmido*:");

        humidSeasonComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        javax.swing.GroupLayout insertPanelLayout = new javax.swing.GroupLayout(insertPanel);
        insertPanel.setLayout(insertPanelLayout);
        insertPanelLayout.setHorizontalGroup(
            insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cell_vivoLabel)
                        .addComponent(passwrod2Label)
                        .addComponent(emailLabel)
                        .addComponent(outPeakDemandContractedField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(createGuidelineButton, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(cell_timLabel)
                    .addComponent(peakDemandContractedField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(drySeasonComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(humidSeasonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        insertPanelLayout.setVerticalGroup(
            insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passwrod2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outPeakDemandContractedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cell_timLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peakDemandContractedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drySeasonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(humidSeasonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(cell_vivoLabel)
                .addGap(484, 484, 484)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createGuidelineButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Inserir", insertPanel);

        guidelineComboBoxEdition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione a Tarifa", "Convencional", "Horo-Sazonal Azul", "Horo-Sazonal Verde" }));

        nameLabel1.setText("*Tipo de Tarifa:");
        nameLabel1.setName(""); // NOI18N

        categoryComboBoxEdition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione a Categoria", "A2 - Comercial/Industrial", "A2 - Poder Público", "A2 - Saneamento (redução de 15%)", "A3a - (30 a 44 kV)", "A3a - Saneamento (redução de 15%)", "A3a - Comercial/Industrial", "A4 - Comercial/Industrial", "A4 - Poder Público", "A4 - Saneamento (redução de 15%)", "A4 - Rural (redução de 10%)", "A4 - Madrugada (redução de 80%)", "A4 - Cooperativa (redução de 50%)", "A4 - Residencial", "AS - Comercial/Industrial", "AS - Poder Público" }));
        categoryComboBoxEdition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxEditionActionPerformed(evt);
            }
        });

        registerLabel1.setText("*Categoria:");

        passwordLabel1.setText("Fora de Ponta:");

        passwrod2Label1.setText("*Custo Demanda:");

        emailLabel1.setText("*Custo Energia Seca:");

        cell_oiLabel1.setText("*Custo Energia Úmida:");

        cell_vivoLabel1.setText("Ponta");

        cell_timLabel1.setText("*Custo Demanda:");

        cell_claroLabel1.setText("*Custo Energia Seca:");

        profileLabel2.setText("*Custo Energia Úmida:");

        warningLabel1.setText("<html>Os campos assinalados com asterisco (*) <br>são de preencimento obrigatório</html>");

        editGuidelineButton.setText("Editar");
        editGuidelineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editGuidelineButtonActionPerformed(evt);
            }
        });

        profileLabel3.setText("*Valor Ultrapassado");

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(passwordLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(editGuidelineButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editPanelLayout.createSequentialGroup()
                                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cell_oiLabel1)
                                    .addComponent(emailLabel1)
                                    .addComponent(passwrod2Label1)
                                    .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(editPanelLayout.createSequentialGroup()
                                            .addComponent(cell_vivoLabel1)
                                            .addGap(113, 113, 113))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cell_claroLabel1)
                                            .addComponent(cell_timLabel1)
                                            .addComponent(profileLabel2))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(outPeakDemandFieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outPeakEnergyDryFieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outPeakEnergyHumidFieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(peakDemandFieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(peakEnergyDryFieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(peakEnergyHumidFieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editPanelLayout.createSequentialGroup()
                                .addComponent(profileLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(valueTranspassedFieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
            .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editPanelLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nameLabel1)
                        .addComponent(registerLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(guidelineComboBoxEdition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(categoryComboBoxEdition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(22, 22, 22)))
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(passwordLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outPeakDemandFieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwrod2Label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outPeakEnergyDryFieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outPeakEnergyHumidFieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell_oiLabel1))
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cell_vivoLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cell_timLabel1)
                        .addGap(13, 13, 13)
                        .addComponent(cell_claroLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(profileLabel2)
                            .addComponent(peakEnergyHumidFieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(peakDemandFieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peakEnergyDryFieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profileLabel3)
                    .addComponent(valueTranspassedFieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE)
                .addComponent(warningLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editGuidelineButton)
                .addGap(17, 17, 17))
            .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editPanelLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLabel1)
                        .addComponent(guidelineComboBoxEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(registerLabel1)
                        .addComponent(categoryComboBoxEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(793, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Editar", editPanel);

        readPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastros Registrados"));

        jTable1.setModel(table);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout readPanelLayout = new javax.swing.GroupLayout(readPanel);
        readPanel.setLayout(readPanelLayout);
        readPanelLayout.setHorizontalGroup(
            readPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        readPanelLayout.setVerticalGroup(
            readPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        backToMainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/house_go.png"))); // NOI18N
        backToMainMenu.setText("Voltar ao Menu Principal");
        backToMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backToMainMenu))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(readPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(readPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backToMainMenu)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backToMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainMenuActionPerformed
        int i;

        Object[] options = {"Sim", "Não"};
        i = JOptionPane.showOptionDialog(null,
                "Deseja realmente Voltar ao Menu Principal?",
                "Voltar ao Menu Principal",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                new ImageIcon("src/icons/house_go.png"),
                options,
                options[1]);

        if (i == JOptionPane.YES_OPTION) {
            MainWindow.desktop.removeAll();
            newMenu = new NewMainMenu(userLogged);
            MainWindow.desktop.add(newMenu);
            MainWindow.desktop.revalidate();
            MainWindow.desktop.repaint();


        }
    }//GEN-LAST:event_backToMainMenuActionPerformed

    private void categoryComboBoxEditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxEditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryComboBoxEditionActionPerformed

    private void editGuidelineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editGuidelineButtonActionPerformed

        String contract = (String) contractComboBoxEdition.getSelectedItem();
        String category = (String) categoryComboBoxEdition.getSelectedItem();
        String peakDemand = peakDemandFieldEdition.getText();
        String outPeakDemand = outPeakDemandFieldEdition.getText();
        String peakEnergyDry = peakEnergyDryFieldEdition.getText();
        String outPeakEnergyDry = outPeakEnergyDryFieldEdition.getText();
        String peakEnergyHumid = peakEnergyHumidFieldEdition.getText();
        String outPeakEnergyHumid = outPeakEnergyHumidFieldEdition.getText();
        String valueTranspassed = valueTranspassedFieldEdition.getText();
        String timestamp = "";

        //@TODO Criar validate
        //valite()

        contractCtrl.createContract(contractRate, category, peakDemand,
                outPeakDemand, peakEnergyDry, outPeakEnergyDry, peakEnergyHumid,
                outPeakEnergyHumid, valueTranspassed, timestamp);

        JOptionPane.showMessageDialog(null, "Edit realizado com sucesso!");

        clean();

        return;
    }//GEN-LAST:event_editGuidelineButtonActionPerformed

    private void createGuidelineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGuidelineButtonActionPerformed
        String contractRate = (String) contractComboBox.getSelectedItem();
        String category = (String) categoryComboBox.getSelectedItem();
        String peakDemand = peakDemandContractedField.getText();
        String outPeakDemand = outPeakDemandField.getText();
        String peakEnergyDry = peakEnergyDryField.getText();
        String outPeakEnergyDry = outPeakEnergyDryField.getText();
        String peakEnergyHumid = peakEnergyHumidField.getText();
        String outPeakEnergyHumid = outPeakEnergyHumidField.getText();
        String valueTranspassed = valueTranspassedField.getText();
        String timestamp = "";

        //@TODO Criar validate
        //valite()

        contractCtrl.createContract(contractRate, category, peakDemand,
            outPeakDemand, peakEnergyDry, outPeakEnergyDry, peakEnergyHumid,
            outPeakEnergyHumid, valueTranspassed, timestamp);

        JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");

        clean();

        return;

    }//GEN-LAST:event_createGuidelineButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMainMenu;
    private javax.swing.JComboBox categoryComboBoxEdition;
    private javax.swing.JLabel cell_claroLabel1;
    private javax.swing.JLabel cell_oiLabel1;
    private javax.swing.JLabel cell_timLabel;
    private javax.swing.JLabel cell_timLabel1;
    private javax.swing.JLabel cell_vivoLabel;
    private javax.swing.JLabel cell_vivoLabel1;
    private javax.swing.JButton createGuidelineButton;
    private javax.swing.JComboBox drySeasonComboBox;
    private javax.swing.JButton editGuidelineButton;
    private javax.swing.JPanel editPanel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JComboBox guidelineComboBoxEdition;
    private javax.swing.JComboBox humidSeasonComboBox;
    private javax.swing.JPanel insertPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JTextField outPeakDemandContractedField;
    private javax.swing.JTextField outPeakDemandFieldEdition;
    private javax.swing.JTextField outPeakEnergyDryFieldEdition;
    private javax.swing.JTextField outPeakEnergyHumidFieldEdition;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JLabel passwrod2Label;
    private javax.swing.JLabel passwrod2Label1;
    private javax.swing.JTextField peakDemandContractedField;
    private javax.swing.JTextField peakDemandFieldEdition;
    private javax.swing.JTextField peakEnergyDryFieldEdition;
    private javax.swing.JTextField peakEnergyHumidFieldEdition;
    private javax.swing.JLabel profileLabel2;
    private javax.swing.JLabel profileLabel3;
    private javax.swing.JPanel readPanel;
    private javax.swing.JLabel registerLabel1;
    private javax.swing.JTextField valueTranspassedFieldEdition;
    private javax.swing.JLabel warningLabel;
    private javax.swing.JLabel warningLabel1;
    // End of variables declaration//GEN-END:variables
}
*/