package view;

import controller.CostCtrl;
import org.jfree.chart.ChartPanel;
import org.jfree.data.time.TimeSeries;


/**
 *
 * @author itallorossi
 */
public class CostChart extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;
    
    private CostCtrl ctrl = new CostCtrl();
    public ChartPanel myChartPanel;
    int state;

    /**
     * Método construtor para construção do gráfico
     * @param x largua
     * @param y altura
     */
    public CostChart(int x, int y) {
        initComponents();
        setSize(x, y);
    }

   /**
    * Método de criação do gráfico.
    * Utilizando gráfico de series
    */ 
    public void criaGrafico(){
        myChartPanel = ctrl.createCostChart();
        myChartPanel.setSize(this.getWidth(), this.getHeight());
        myChartPanel.setVisible(true);
        this.removeAll();
        this.add(myChartPanel);
        this.revalidate();
        this.repaint();
           
        
        state = 1;
    }
      public TimeSeries getSeries() {
        return ctrl.getAllSeries();
    }
      
     public TimeSeries limitSeries(){
         return ctrl.limitSeries();
     }
    
    /**
     * Método para alteração do tamanho
     * @param x largura
     * @param y altura
     */
    public void changeSize(int x, int y) {
        if (state != 0) {
            myChartPanel.setSize(x, y);
            this.setSize(x, y);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
