package view;

import controller.LoadCurveCtrl;
import java.awt.Color;
import java.awt.Font;
import model.LoadCurve;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.annotations.XYPointerAnnotation;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.time.Millisecond;
import org.jfree.data.time.Second;
import org.jfree.data.time.TimeSeries;
import org.jfree.data.time.TimeSeriesCollection;
import org.jfree.ui.TextAnchor;

/**
 *
 * @author itallorossi
 */
public class EstimationOnRealLoadChart extends javax.swing.JPanel {
    public TimeSeries series, estimate;
    public JFreeChart chart;
    public ChartPanel chartPanel;
    public ValueAxis xAxis;
    public ValueAxis yAxis;
    int state;

    /**
     * Creates new form CharPanel
     */
    public EstimationOnRealLoadChart(int x, int y) {
        initComponents();
        setSize(x, y);
    }
    
    public void createLoadCurveGraphPanel() {
        this.series = new TimeSeries("Carga Real (kWh)", Millisecond.class);
        this.estimate = new TimeSeries("Carva Estimada (kWh)", Second.class);
        TimeSeriesCollection dataset = new TimeSeriesCollection(this.series);
        dataset.addSeries(estimate);

        this.chart = ChartFactory.createTimeSeriesChart("Estimativa de Carga", "Hora", "Potência Ativa (kWh)", dataset, true, true, false);

        XYPlot xyplot = (XYPlot) this.chart.getPlot();
        xyplot.setBackgroundPaint(Color.lightGray);
        xyplot.setForegroundAlpha(0.65F);
        xyplot.setDomainGridlinePaint(Color.white);
        xyplot.setRangeGridlinePaint(Color.white);

        this.xAxis = xyplot.getDomainAxis();

        this.xAxis.setTickMarkPaint(Color.black);
        this.xAxis.setRange(0, 86400000); // 24 horas = 86400000 mili
        this.xAxis.setAutoRange(true);
        this.xAxis.setFixedAutoRange(60000.0);

        this.yAxis = xyplot.getRangeAxis();
        this.yAxis.setRange(0, 6);
        this.yAxis.setAutoRange(true);

        XYPointerAnnotation xypointerannotation = new XYPointerAnnotation("Test", 5D, -500D, 2.3561944901923448D);
        xypointerannotation.setTipRadius(0.0D);
        xypointerannotation.setBaseRadius(35D);
        xypointerannotation.setFont(new Font("SansSerif", 0, 9));
        xypointerannotation.setPaint(Color.blue);
        xypointerannotation.setTextAnchor(TextAnchor.HALF_ASCENT_RIGHT);
        xyplot.addAnnotation(xypointerannotation);

        this.chartPanel = new ChartPanel(this.chart, true);
    }

    public void startGraph() {
        createLoadCurveGraphPanel();
        ChartPanel panel = this.chartPanel;
        panel.setSize(this.getWidth(), this.getHeight());
        panel.setVisible(true);
        this.removeAll();
        this.add(panel);
        this.revalidate();
        this.repaint();
        state = 1;
    }


    public void changeSize(int x, int y) {
        if (state != 0) {
            chartPanel.setSize(x, y);
            this.setSize(x, y);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
